name: devpack-for-spring-manifest
build-base: core24
base: bare
license: Apache-2.0
adopt-info: devpack-for-spring-manifest
summary: The list of all available content snaps for Spring®
description: |
  The Devpack for Spring® manifest is a list of all content snaps
  available to be downloaded by the Devpack for Spring® snap.

grade: stable
confinement: strict

parts:
  devpack-for-spring-manifest:
    plugin: nil
    source: .
    build-packages:
      - git
      - yamllint
      - yq
      - python3
    override-build: |
      yamllint supported.yaml
      ./generate-manifest.py supported.yaml supported.versions.toml \
        ${CRAFT_PART_INSTALL}/supported.yaml
      cp LICENSE ${CRAFT_PART_INSTALL}/
      craftctl set version="$(yq .version supported.yaml)"
      craftctl default
