name: devpack-for-spring
base: bare
build-base: core24
version: '1.2.0'
license: Apache-2.0
summary: Development tools for Spring® projects
title: Development tools for Spring® projects
issues:
  - https://github.com/canonical/devpack-for-spring/issues
contact:
- https://github.com/canonical/devpack-for-spring/issues
source-code:
  - https://github.com/canonical/devpack-for-spring/
website:
  - https://github.com/canonical/devpack-for-spring/
description: |
  Development tools for Spring® projects.

  The snap packages a tool based on Spring CLI project with additional
  commands.

  Snap documentation:
  https://github.com/canonical/spring-boot-snap/blob/main/devpack-for-spring/README.md

  Spring is a trademark of Broadcom Inc. and/or its subsidiaries.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots

platforms:
  amd64:
  arm64:

parts:
  build-cli:
    plugin: nil
    source: https://github.com/canonical/devpack-for-spring-cli
    source-type: git
    source-tag: 0.12.1
    stage-packages:
      - libc6_libs
      - libgcc-s1_libs
      - libstdc++6_libs
      - zlib1g_libs
      - libnss3_libs
      - bash_bins
    build-attributes:
      - enable-patchelf
    build-environment:
      - JAVA_HOME: /snap/graalvm-jdk/current/graalvm-ce/
    build-snaps:
      - graalvm-jdk/v21/stable
      - gradle/latest/stable
    override-build: |
      gradle --no-daemon build \
        nativeCompile -PcliNative=true \
        -x test
      mkdir -p $CRAFT_PART_INSTALL/cli/
      cp build/native/nativeCompile/* $CRAFT_PART_INSTALL/cli/
      craftctl default

  install-cli:
    plugin: nil
    source: .
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/cli/
      cp cli.sh $CRAFT_PART_INSTALL/cli/
      craftctl default

  plugin-config:
    plugin: dump
    source: .
    stage:
      - plugin-configuration.yaml
      - setup-configuration.yaml

apps:
  devpack-for-spring:
    command: cli/cli.sh
