name: devpack-for-spring
base: bare
build-base: core24
version: '1.2.2'
license: Apache-2.0
summary: Development tools for Spring® projects
title: Development tools for Spring® projects
issues:
  - https://github.com/canonical/devpack-for-spring/issues
contact:
- https://github.com/canonical/devpack-for-spring/issues
source-code:
  - https://github.com/canonical/devpack-for-spring/
website:
  - https://github.com/canonical/devpack-for-spring/
description: |
  Command line tool for developing and packaging Spring(R) projects.
  Automates environment setup, build plugins configuration and offline
  library management.
  Type devpack-for-spring help after installation to start.

  Snap documentation: https://github.com/canonical/devpack-for-spring/blob/main/devpack-for-spring/README.md

  Spring is a trademark of Broadcom Inc. and/or its subsidiaries.
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots

platforms:
  amd64:
  arm64:

parts:
  build-cli:
    plugin: nil
    source: https://github.com/canonical/devpack-for-spring-cli
    source-type: git
    source-branch: 0.12.4
    stage-packages:
      - bash_bins
      - openjdk-25-jdk-headless_standard
    build-attributes:
      - enable-patchelf
    build-snaps:
      - gradle/latest/stable
    build-packages:
      - openjdk-25-jdk-headless
    override-build: |
      gradle --no-daemon -Paot=true build -x test

      mkdir -p "$CRAFT_PART_INSTALL/cli"
      find build/libs/ -name "devpack-for-spring-cli-*.jar" ! -name "*-plain.jar" \
        -exec cp {} "$CRAFT_PART_INSTALL/cli/devpack-for-spring-cli.jar" \; -quit

      JAVA_HOME="usr/lib/jvm/java-25-openjdk-${CRAFT_ARCH_BUILD_FOR}"
      cd "$CRAFT_PART_INSTALL"
      mkdir -p usr/bin
      for tool in `ls "$CRAFT_PART_INSTALL/$JAVA_HOME/bin"`; do
        ln -s --relative "$JAVA_HOME/bin/$tool" usr/bin/
      done

      craftctl default

  install-cli:
    plugin: nil
    source: .
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/cli/
      cp cli.sh $CRAFT_PART_INSTALL/cli/
      craftctl default

  plugin-config:
    plugin: dump
    source: .
    stage:
      - plugin-configuration.yaml
      - setup-configuration.yaml

apps:
  devpack-for-spring:
    command: cli/cli.sh
