name: devpack-for-spring
base: bare
build-base: core24
version: '1.1.0'
license: Apache-2.0
summary: Development tools for Spring® projects
description: |
  Development tools for Spring® projects.

  The snap packages a tool based on Spring CLI project with additional
  commands.

  Snap documentation:
  https://github.com/canonical/spring-boot-snap/blob/main/devpack-for-spring/README.md

  Spring is a trademark of Broadcom Inc. and/or its subsidiaries.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots

platforms:
  amd64:
  arm64:

parts:
  build-cli:
    plugin: nil
    source: https://github.com/canonical/devpack-for-spring-cli
    source-type: git
    source-tag: 0.11.1
    stage-packages:
      - libc6
      - libgcc-s1
      - libstdc++6
      - zlib1g
      - libnss3
    build-attributes:
      - enable-patchelf
    build-environment:
      - JAVA_HOME: /snap/graalvm-jdk/current/graalvm-ce/
    build-snaps:
      - graalvm-jdk/v21/stable
      - gradle/latest/edge
    override-build: |
      gradle --no-daemon build \
        nativeCompile -PcliNative=true \
        -x test
      mkdir -p $CRAFT_PART_INSTALL/cli/
      cp build/native/nativeCompile/* $CRAFT_PART_INSTALL/cli/
      craftctl default

  plugin-config:
    plugin: dump
    source: .
    stage:
      - build-plugins.yaml

apps:
  devpack-for-spring:
    command: cli/devpack-for-spring-cli
