format:
  gradle:
    id: io.spring.javaformat
    version: 0.0.47
    default-task: format
    description: Format the source code
    tasks:
      - format: format
    repository: gradlePluginPortal()
  maven:
    id: io.spring.javaformat:spring-javaformat-maven-plugin
    version: 0.0.47
    default-task: format
    description: Format the source code
    tasks:
      - format: :apply
dependencies:
  gradle:
    id: io.github.rockcrafters.rockcraft
    version: 1.2.4
    repository: gradlePluginPortal()
    default-task: dependencies-export
    description: |
      Save project dependencies
    tasks:
      - dependencies-export: dependencies-export
  maven:
    id: io.github.rockcrafters:rockcraft-maven-plugin
    version: 1.2.4
    default-task: dependencies-export
    description: |
      Save project dependencies
    tasks:
      - dependencies-export: :create-build-rock
rockcraft:
  gradle:
    id: io.github.rockcrafters.rockcraft
    version: 1.2.4
    repository: gradlePluginPortal()
    default-task: build-rock
    description: |
      Plugin for rock image generation
    tasks:
      - create-rock: create-rock
      - build-rock: build-rock
      - create-build-rock: create-build-rock
      - build-build-rock: build-build-rock
      - push-rock: push-rock
      - push-build-rock: push-build-rock
  maven:
    id: io.github.rockcrafters:rockcraft-maven-plugin
    version: 1.2.4
    default-task: build-rock
    description: |
      Plugin for rock image generation
    tasks:
      - create-rock:
        - install
        - :create-rock
      - build-rock:
        - install
        - :create-rock
        - :build-rock
      - create-build-rock:
        - :create-build-rock
      - push-rock:
        - install
        - :create-rock
        - :build-rock
        - :push-rock
      - push-build-rock:
        - install
        - :create-build-rock
        - :build-build-rock
        - :push-build-rock
