# Top level menu item
java:
  # Menu text
  description: OpenJDK
  # Single or multi-selection menu
  multiselect: true
  # apt packages to install
  apt:
    # Package name
    - openjdk-8-jdk:
        # Menu item text
        description: OpenJDK 8
    - openjdk-11-jdk:
        description: OpenJDK 11
    - openjdk-17-jdk:
        description: OpenJDK 17
    - openjdk-21-jdk:
        description: OpenJDK 21
  # snap packages to install
  snap:
    # snap name
    - graalvm-jdk:
        # Menu item text
        description: GraalVM Community Edition for the Java Development Kit
docker:
  description: Container environment
  apt:
    - docker.io:
        description: docker.io - Docker container runtime
        # post-installation commands
        # they can be used to set up user groups,
        # connect snap interfaces or refresh the snap to the
        # desired channel
        extra-commands:
          - sudo usermod -aG docker ${user.name}
          - echo Please logout and login or run 'newgrp docker' to apply the group changes.
    - podman:
        description: podman - A daemon-less alternative to docker
        extra-commands:
          - sudo apt-get -y install podman-docker
  snap:
    - docker:
        description: docker - Docker container runtime snap
        extra-commands:
          - sudo snap connect docker:privileged :docker-support
          - sudo snap connect docker:support :docker-support
          - sudo snap connect docker:firewall-control :firewall-control
          - sudo snap connect docker:network-control :network-control
          - sudo snap connect docker:docker-cli docker:docker-daemon
          - sudo snap connect docker:home
          - sudo snap disable docker
          - sudo snap enable docker
ide:
  description: Integrated Development Environment
  multiselect: true
  snap:
    - intellij-idea-community:
        classic: true
        description: Intellij Idea Community snap
    - eclipse:
        classic: true
        description: Eclipse snap
    - code:
        classic: true
        description: Visual Studio Code snap
        extra-commands:
          - code --install-extension redhat.java --force
          - code --install-extension ms-azuretools.vscode-containers  --force
          - code --install-extension vmware.vscode-spring-boot --force
          - code --install-extension vmware.vscode-boot-dev-pack --force
misc:
  description: Additional tools
  snap:
    - snapcraft:
        classic: true
        description: snapcraft - easily create snaps
    - rockcraft:
        classic: true
        description: rockcraft - a craft like experience to create rocks
  apt:
    - git:
        description: git - fast, scalable, distributed revision control system
