name: Build on main

on:
  push:
    branches: main
    tags:
  pull_request:
    branches: main
  workflow_dispatch:

permissions:
  checks: write
  pull-requests: write

jobs:

  snapcraft-build:
    strategy:
      matrix:
        os:
          - [self-hosted, large, jammy, X64]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        id: checkout

      - name: Run content snap generator
        id: gen-content
        run: make prepare

      - name: Build devpack
        id: devpack-for-spring
        uses: snapcore/action-build@v1
        with:
          path: devpack-for-spring

      - name: Upload Snap to workflow artifacts
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: devpack-for-spring
          path: ${{ steps.devpack-for-spring.outputs.snap }}

      - name: Build manifest
        id: devpack-for-spring-manifest
        uses: snapcore/action-build@v1
        with:
          path: devpack-for-spring-manifest

      - name: Upload Snap to workflow artifacts
        id: upload-artifact-manifest
        uses: actions/upload-artifact@v4
        with:
          name: devpack-for-spring-manifest
          path: ${{ steps.devpack-for-spring-manifest.outputs.snap }}


  snapcraft-publish:
    runs-on: ubuntu-latest
    if: ${{ contains(fromJSON('["push", "workflow_dispatch"]'), github.event_name) && github.ref_name == 'main' }}
    needs: snapcraft-build
    strategy:
      matrix:
        artifact-name:
          - devpack-for-spring
          - devpack-for-spring-manifest
    steps:
      - uses: actions/download-artifact@v4
        id: download-artifact
        with:
          name: ${{ matrix.artifact-name }}

      - name: Gather filename
        id: gather-filename-devpack
        env:
          ARTIFACT_PATH: ${{ steps.download-artifact.outputs.download-path }}
        run: |
          set -ex
          ls -la $ARTIFACT_PATH
          SNAP_FILE_NAME=$(ls ${ARTIFACT_PATH}/devpack-for-spring*.snap)
          echo "SNAP_PATH=${SNAP_FILE_NAME}" >> "$GITHUB_OUTPUT"

      - name: Set release channel
        run: |
            if [[ "$GITHUB_REF_TYPE" == "tag" ]]; then
              echo "CHANNEL=stable" >> $GITHUB_ENV
            else
              echo "CHANNEL=edge" >> $GITHUB_ENV
            fi

      - uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPSTORE_LOGIN }}
        with:
          snap: ${{ steps.gather-filename-devpack.outputs.SNAP_PATH }}
          release:  ${{ env.CHANNEL }}
